nnets: {}
prod:
  SpecialSymbols:
    - "<unk>"
    - "<pad>"
    - "<bos>"
    - "<eos>"
  onnx_path: "../resources"
  vocab_transform: "../resources/vocab_transform.yaml"
  TargetCHARS: "ACMSXZabcdefghijklmnopqrstuvwxyz"
transliteration:
  SOURCECHARS: " ءآأؤئابةتثجحخدذرزسشصضطظعغـفقلمنهوَِْپچژکگی \u200c "
  window: 6
  space: 4
  preprocessData: false
