nnets: {}
transliteration:
  SourceCHARS: "abcdefghijklmnopqrstuvwxyz "
  SpecialSymbols:
    - "<unk>"
    - "<pad>"
    - "<bos>"
    - "<eos>"
  onnx_path: "../resources"
  vocab_transform: "../resources/vocab_transform.yaml"
  TargetCHARS: "abcdefghijklmnopqrstuvwxyz "
