nnets:
  EMB_SIZE: 512
  NHEAD: 8
  FFN_HID_DIM: 512
  BATCH_SIZE: 32
  NUM_ENCODER_LAYERS: 3
  NUM_DECODER_LAYERS: 3
  TRAIN_DATA: "../learn-graph/data/test_train.txt" # train data for nnets
  TEST_DATA: "../learn-graph/data/test_benchmark.csv" # test data for nnets
  VOCAB_TRAFO: "data/vocab_transform.pickle" # vocab trafo

transliteration:
  preprocessData: true
  SOURCECHARS: "abcdefghijklmnopqrstuvwxyz "
  TARGETCHARS: "abcdefghijklmnopqrstuvwxyz "
  window: 6
  onnx_path: "../resources"
  space: 4
  max_str_len: 100
  vocab_transform: "../resources/vocab_transform.yaml"
  TRAIN_DATA: "../learn-graph/data/test_train.txt"
  SPECIALSYMBOLS:
    - "<unk>"
    - "<pad>"
    - "<bos>"
    - "<eos>"
